"""add outbox model attempts fields

Revision ID: 442767ee0755
Revises: c481aa66bf7c
Create Date: 2026-06-26 23:03:41.700288

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "442767ee0755"
down_revision: Union[str, Sequence[str], None] = "c481aa66bf7c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "outbox_events",
        sa.Column("idempotency_key", sa.String(length=64), nullable=False),
    )
    op.add_column(
        "outbox_events",
        sa.Column("message", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    )
    op.add_column("outbox_events", sa.Column("attempt", sa.Integer(), nullable=False))
    op.add_column(
        "outbox_events",
        sa.Column("max_attempts", sa.Integer(), nullable=False),
    )
    op.create_unique_constraint(
        op.f("uq_outbox_events_idempotency_key"),
        "outbox_events",
        ["idempotency_key"],
    )
    op.drop_constraint(
        op.f("fk_outbox_events_payment_id_payments"),
        "outbox_events",
        type_="foreignkey",
    )
    op.drop_column("outbox_events", "payment_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "outbox_events",
        sa.Column("payment_id", sa.UUID(), autoincrement=False, nullable=False),
    )
    op.create_foreign_key(
        op.f("fk_outbox_events_payment_id_payments"),
        "outbox_events",
        "payments",
        ["payment_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        op.f("uq_outbox_events_idempotency_key"),
        "outbox_events",
        type_="unique",
    )
    op.drop_column("outbox_events", "max_attempts")
    op.drop_column("outbox_events", "attempt")
    op.drop_column("outbox_events", "message")
    op.drop_column("outbox_events", "idempotency_key")
    # ### end Alembic commands ###
