"""init

Revision ID: 8cee23f10b17
Revises:
Create Date: 2026-06-25 01:01:34.747786

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "8cee23f10b17"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "payments",
        sa.Column("amount", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column(
            "currency",
            sa.Enum("USD", "RUB", "EUR", name="currency_type_enum"),
            nullable=False,
        ),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.Column("meta_info", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "status",
            sa.Enum("PENDING", "SUCCESS", "FAILED", name="payment_status_enum"),
            nullable=False,
        ),
        sa.Column("idempotency_key", sa.String(length=64), nullable=False),
        sa.Column("webhook_url", sa.String(length=2048), nullable=False),
        sa.Column("processing_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "amount > 0",
            name=op.f("ck_payments_check_payment_amount_positive"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_payments")),
        sa.UniqueConstraint(
            "idempotency_key", name=op.f("uq_payments_idempotency_key")
        ),
    )
    op.create_index(
        "ix_payments_status_created_at",
        "payments",
        ["status", "created_at"],
        unique=False,
    )
    op.create_table(
        "outbox_events",
        sa.Column("payment_id", sa.Uuid(), nullable=False),
        sa.Column("exchange", sa.String(length=255), nullable=False),
        sa.Column("routing_key", sa.String(length=255), nullable=False),
        sa.Column("is_processed", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["payment_id"],
            ["payments.id"],
            name=op.f("fk_outbox_events_payment_id_payments"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_outbox_events")),
    )
    op.create_index(
        op.f("ix_outbox_events_is_processed"),
        "outbox_events",
        ["is_processed"],
        unique=False,
    )
    op.create_index(
        "ix_outbox_unprocessed_created_at",
        "outbox_events",
        ["created_at"],
        unique=False,
        postgresql_where="is_processed = FALSE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_outbox_unprocessed_created_at",
        table_name="outbox_events",
        postgresql_where="is_processed = FALSE",
    )
    op.drop_index(op.f("ix_outbox_events_is_processed"), table_name="outbox_events")
    op.drop_table("outbox_events")
    op.drop_index("ix_payments_status_created_at", table_name="payments")
    op.drop_table("payments")
    # ### end Alembic commands ###
