"""update outbox model queue field

Revision ID: c481aa66bf7c
Revises: 8cee23f10b17
Create Date: 2026-06-26 06:19:13.840138

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "c481aa66bf7c"
down_revision: Union[str, Sequence[str], None] = "8cee23f10b17"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "outbox_events",
        sa.Column("queue", sa.String(length=255), nullable=False),
    )
    op.drop_column("outbox_events", "routing_key")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "outbox_events",
        sa.Column(
            "routing_key",
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("outbox_events", "queue")
    # ### end Alembic commands ###
