"""update outbox model

Revision ID: ef56f9aa3024
Revises: 442767ee0755
Create Date: 2026-06-27 01:59:56.675777

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "ef56f9aa3024"
down_revision: Union[str, Sequence[str], None] = "442767ee0755"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("outbox_events", "max_attempts")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "outbox_events",
        sa.Column("max_attempts", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    # ### end Alembic commands ###
